### ISSUE TITLE
Import third party module issue

### ISSUE THREAD

**Issue by 0xbear9999** [solana-playground/solana-playground#237] opened 2024-05-21 04:44 UTC
I'd like to import third party modules as dependencies, but cant find cargo.toml and not sure how to add cargo packages on solpg
If anyone can guide me or share such experience, I will appreciate it
Thanks

**Comment by acheroncrypto** [comment] 2024-05-22 07:36
It would be great to support this eventually but it's not currently supported. Please see https://github.com/solana-playground/solana-playground/issues/217#issuecomment-2029761904 for the reasoning.

Closing because it's a duplicate of https://github.com/solana-playground/solana-playground/issues/217.

**Closed** 2024-05-22 13:39 UTC
Labels: duplicate, question
